spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/library_db?useUnicode=true&character_set_server=utf8mb4
    username: root
    password: mywatchlibrarysql
    driverClassName: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE